# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nst < Formula
  desc "Force terminate stuck Kubernetes namespaces"
  homepage "https://github.com/alihamzaoriginal/namespace-terminator"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_darwin_amd64.tar.gz"
      sha256 "4af53508b600f78b0d91a73eca5eedcc36dbd06de898fa98d91d0d7d46cb04b6"

      define_method(:install) do
        bin.install "nst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_darwin_arm64.tar.gz"
      sha256 "9f65c8c1b804127b6be5c1d99ed900a946a137ac090acfe465bc341d13a50095"

      define_method(:install) do
        bin.install "nst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_linux_amd64.tar.gz"
      sha256 "74ea32d8cd37827521d0849a2d77467ad7b0a06255c6657d91295b3438e71a00"
      define_method(:install) do
        bin.install "nst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_linux_arm64.tar.gz"
      sha256 "2055713a9661359d0cf0c7676863e2eaa13619af55df5a1fa19fb650bb31fce6"
      define_method(:install) do
        bin.install "nst"
      end
    end
  end

  test do
    system "#{bin}/nst", "--help"
  end
end
