# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nst < Formula
  desc "Force terminate stuck Kubernetes namespaces"
  homepage "https://github.com/alihamzaoriginal/namespace-terminator"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_darwin_amd64.tar.gz"
      sha256 "bd85dafbd95db5c80198fc67c46315912c0e02687b7fab135663fba778727672"

      define_method(:install) do
        bin.install "nst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_darwin_arm64.tar.gz"
      sha256 "a2d1180bc9d7ffb644b1b9c4affee084b042272b8d91b0c210d434ab5294fbd5"

      define_method(:install) do
        bin.install "nst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_linux_amd64.tar.gz"
      sha256 "ed4e005b01e423a6f41f8b505207ea13ca884c481ac9a8d75e9482058d906212"
      define_method(:install) do
        bin.install "nst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_linux_arm64.tar.gz"
      sha256 "416dc5693f8e4b96f750d17f6951b3582fb41fa93ffe09710c1f4daa603d95ae"
      define_method(:install) do
        bin.install "nst"
      end
    end
  end

  test do
    system "#{bin}/nst", "--help"
  end
end
