# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nst < Formula
  desc "Force terminate stuck Kubernetes namespaces"
  homepage "https://github.com/alihamzaoriginal/namespace-terminator"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_darwin_amd64.tar.gz"
      sha256 "7f0b97412f5ce5d696f53c8395f22514e88721e2eb0a16f0eb51d7d6ee2b09c5"

      define_method(:install) do
        bin.install "nst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_darwin_arm64.tar.gz"
      sha256 "a259f83ba549e0528987995a9ec576b89469c3d355e9e7112756a3ba6af42659"

      define_method(:install) do
        bin.install "nst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_linux_amd64.tar.gz"
      sha256 "a83f36b0ce339660356b92c02c75467539b09111f078ebe507291bd9f6e92b5f"
      define_method(:install) do
        bin.install "nst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/namespace-terminator/releases/download/v1.0.0/nst_1.0.0_linux_arm64.tar.gz"
      sha256 "98cdb686ac85ebd486e96bbf8f7dd402486cfecdf9b52542fcc9f37c01c8b7a9"
      define_method(:install) do
        bin.install "nst"
      end
    end
  end

  test do
    system "#{bin}/nst", "--help"
  end
end
