# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfpeek < Formula
  desc "Dry-run Terraform/OpenTofu plan summaries grouped by change type"
  homepage "https://github.com/alihamzaoriginal/tfpeek"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alihamzaoriginal/tfpeek/releases/download/v1.0.0/tfpeek_1.0.0_darwin_amd64.tar.gz"
      sha256 "6ad6207193cb9cd07f92698b1b25d5f9a118a266a2d56188c8a8d0d059df5e63"

      define_method(:install) do
        bin.install "tfpeek"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alihamzaoriginal/tfpeek/releases/download/v1.0.0/tfpeek_1.0.0_darwin_arm64.tar.gz"
      sha256 "c6bef0e7d54c3100c71fa3d5875e1d97efe976b0faa7e96555194958bac398da"

      define_method(:install) do
        bin.install "tfpeek"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/tfpeek/releases/download/v1.0.0/tfpeek_1.0.0_linux_amd64.tar.gz"
      sha256 "a063212d70def1c52c8c7123034b8102c8e454507d5eeddcdfa292346d3d1f90"
      define_method(:install) do
        bin.install "tfpeek"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alihamzaoriginal/tfpeek/releases/download/v1.0.0/tfpeek_1.0.0_linux_arm64.tar.gz"
      sha256 "af707aeaa950c2bfb88588081bd4b1bc94b78209198b93986c38c132a64a4038"
      define_method(:install) do
        bin.install "tfpeek"
      end
    end
  end

  test do
    system "#{bin}/tfpeek", "--help"
  end
end
